#
# Module manifest for module 'VMware.PowerCLI'
#
# Generated by: "VMware"
#

@{

# Script module or binary module file associated with this manifest
#ModuleToProcess = ''

# Version number of this module.
ModuleVersion = '13.3.0.24145083'

# ID used to uniquely identify this module
GUID = '16e76051-92c2-41c7-bdc6-ba2a467a7fd3'

# Author of this module
Author = 'Broadcom'

# Company or vendor of this module
CompanyName = 'Broadcom, Inc.'

# Copyright statement for this module
Copyright = 'Copyright (c) Broadcom. All Rights Reserved.'

# Description of the functionality provided by this module
Description = 'This module is deprecated. Please use the module VCF.PowerCLI instead. For more information, see https://developer.broadcom.com/powercli/installation-guide'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
@{"ModuleName"="VMware.VimAutomation.Sdk";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Common";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.Vim";"RequiredVersion"="8.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Cis.Core";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Core";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Storage";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Srm";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.License";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Vds";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.CloudServices";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Vmc";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Nsxt";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.vROps";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Cloud";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.ImageBuilder";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.DeployAutomation";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.StorageUtility";"RequiredVersion"="1.6.0.0"}
@{"ModuleName"="VMware.VumAutomation";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Security";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.Hcx";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.VimAutomation.WorkloadManagement";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.Sdk.Runtime";"RequiredVersion"="1.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphereRuntime";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.Access";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.Health";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.InfraProfile";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.LocalAccounts";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.Logging";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.Networking";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.Recovery";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.SupportBundle";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.System";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.Tls";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Appliance.Update";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Cis";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Cis.Tagging";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Content";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.ContentLibrary";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Esx.Hcl";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Esx.Hosts";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.Esx.Settings";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.SnapService";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.VAPI.Metadata";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Authentication";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Authorization";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.CertManagement";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.ConsumptionDomains";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Content";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Datastore";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Deployment";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Guest";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.HVC";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Identity";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Inventory";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.ISO";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.LCM";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.NamespaceManagement";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Namespaces";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.OVF";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Services";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Storage";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.SystemConfig";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Tagging";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Topology";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.TrustedInfrastructure";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.VCHA";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.Vm";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vCenter.VmTemplate";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere.vStats";"RequiredVersion"="8.0.2099.24145081"}
@{"ModuleName"="VMware.Sdk.vSphere";"RequiredVersion"="13.3.2099.24145081"}
@{"ModuleName"="VMware.PowerCLI.Sdk.Types";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.PowerCLI.Sdk";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.PowerCLI.VCenter.Types.ApplianceService";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.PowerCLI.VCenter.Types.CertificateManagement";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.PowerCLI.VCenter";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.Sdk.Nsx.Policy";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.Sdk.Srm";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.Sdk.Vr";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.Sdk.Vcf.CloudBuilder";"RequiredVersion"="13.3.0.24145081"}
@{"ModuleName"="VMware.Sdk.Vcf.SddcManager";"RequiredVersion"="13.3.0.24145081"}
)

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
#FormatsToProcess = ''

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules= @('VMware.PowerCLI.ps1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList =	@()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

    # Tags applied to this module. These help with module discovery in online galleries.
    # Tags = @()

    # A URL to the license for this module.
    # LicenseUri = ''

    # A URL to the main website for this project.
    ProjectUri = 'https://developer.broadcom.com/powercli'

    # A URL to an icon representing this module.
    IconUri = 'https://raw.githubusercontent.com/vmware/PowerCLI-Example-Scripts/1710f7ccbdd9fe9a3ab3f000e920fa6e8e042c63/resources/powercli-psgallery-icon.svg'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}

# SIG # Begin signature block
# MIIpgQYJKoZIhvcNAQcCoIIpcjCCKW4CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCD+3MTB353UrqpE
# BzVX+cyBwKxiNfPuUosF+o0+HQtKI6CCDnQwggawMIIEmKADAgECAhAIrUCyYNKc
# TJ9ezam9k67ZMA0GCSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNV
# BAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9vdCBHNDAeFw0yMTA0MjkwMDAwMDBaFw0z
# NjA0MjgyMzU5NTlaMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwg
# SW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcg
# UlNBNDA5NiBTSEEzODQgMjAyMSBDQTEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
# ggIKAoICAQDVtC9C0CiteLdd1TlZG7GIQvUzjOs9gZdwxbvEhSYwn6SOaNhc9es0
# JAfhS0/TeEP0F9ce2vnS1WcaUk8OoVf8iJnBkcyBAz5NcCRks43iCH00fUyAVxJr
# Q5qZ8sU7H/Lvy0daE6ZMswEgJfMQ04uy+wjwiuCdCcBlp/qYgEk1hz1RGeiQIXhF
# LqGfLOEYwhrMxe6TSXBCMo/7xuoc82VokaJNTIIRSFJo3hC9FFdd6BgTZcV/sk+F
# LEikVoQ11vkunKoAFdE3/hoGlMJ8yOobMubKwvSnowMOdKWvObarYBLj6Na59zHh
# 3K3kGKDYwSNHR7OhD26jq22YBoMbt2pnLdK9RBqSEIGPsDsJ18ebMlrC/2pgVItJ
# wZPt4bRc4G/rJvmM1bL5OBDm6s6R9b7T+2+TYTRcvJNFKIM2KmYoX7BzzosmJQay
# g9Rc9hUZTO1i4F4z8ujo7AqnsAMrkbI2eb73rQgedaZlzLvjSFDzd5Ea/ttQokbI
# YViY9XwCFjyDKK05huzUtw1T0PhH5nUwjewwk3YUpltLXXRhTT8SkXbev1jLchAp
# QfDVxW0mdmgRQRNYmtwmKwH0iU1Z23jPgUo+QEdfyYFQc4UQIyFZYIpkVMHMIRro
# OBl8ZhzNeDhFMJlP/2NPTLuqDQhTQXxYPUez+rbsjDIJAsxsPAxWEQIDAQABo4IB
# WTCCAVUwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUaDfg67Y7+F8Rhvv+
# YXsIiGX0TkIwHwYDVR0jBBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0P
# AQH/BAQDAgGGMBMGA1UdJQQMMAoGCCsGAQUFBwMDMHcGCCsGAQUFBwEBBGswaTAk
# BggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAC
# hjVodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9v
# dEc0LmNydDBDBgNVHR8EPDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5j
# b20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNybDAcBgNVHSAEFTATMAcGBWeBDAED
# MAgGBmeBDAEEATANBgkqhkiG9w0BAQwFAAOCAgEAOiNEPY0Idu6PvDqZ01bgAhql
# +Eg08yy25nRm95RysQDKr2wwJxMSnpBEn0v9nqN8JtU3vDpdSG2V1T9J9Ce7FoFF
# UP2cvbaF4HZ+N3HLIvdaqpDP9ZNq4+sg0dVQeYiaiorBtr2hSBh+3NiAGhEZGM1h
# mYFW9snjdufE5BtfQ/g+lP92OT2e1JnPSt0o618moZVYSNUa/tcnP/2Q0XaG3Ryw
# YFzzDaju4ImhvTnhOE7abrs2nfvlIVNaw8rpavGiPttDuDPITzgUkpn13c5Ubdld
# AhQfQDN8A+KVssIhdXNSy0bYxDQcoqVLjc1vdjcshT8azibpGL6QB7BDf5WIIIJw
# 8MzK7/0pNVwfiThV9zeKiwmhywvpMRr/LhlcOXHhvpynCgbWJme3kuZOX956rEnP
# LqR0kq3bPKSchh/jwVYbKyP/j7XqiHtwa+aguv06P0WmxOgWkVKLQcBIhEuWTatE
# QOON8BUozu3xGFYHKi8QxAwIZDwzj64ojDzLj4gLDb879M4ee47vtevLt/B3E+bn
# KD+sEq6lLyJsQfmCXBVmzGwOysWGw/YmMwwHS6DTBwJqakAwSEs0qFEgu60bhQji
# WQ1tygVQK+pKHJ6l/aCnHwZ05/LWUpD9r4VIIflXO7ScA+2GRfS0YW6/aOImYIbq
# yK+p/pQd52MbOoZWeE4wgge8MIIFpKADAgECAhAGQAJb/wxIlzKZ1GMgg8N7MA0G
# CSqGSIb3DQEBCwUAMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwg
# SW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcg
# UlNBNDA5NiBTSEEzODQgMjAyMSBDQTEwHhcNMjQwMzI4MDAwMDAwWhcNMjcwMzMw
# MjM1OTU5WjCBxDETMBEGCysGAQQBgjc8AgEDEwJVUzEZMBcGCysGAQQBgjc8AgEC
# EwhEZWxhd2FyZTEdMBsGA1UEDwwUUHJpdmF0ZSBPcmdhbml6YXRpb24xEDAOBgNV
# BAUTBzY2MTAxMTcxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMREw
# DwYDVQQHEwhTYW4gSm9zZTEVMBMGA1UEChMMQnJvYWRjb20gSW5jMRUwEwYDVQQD
# EwxCcm9hZGNvbSBJbmMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC6
# 8C+jJxKfxp9c1A6fghwSNjnvV+Y1my2XmTHEPmk7COFTWw1VRBZBtv/zUXrSStlW
# 9Qqqp48wk+H+H5oM0qL9jsUQ6wAJpmjt33F3xvKqc8ehzVZLXUEACQBXTo30Hnbh
# bcacKAyX9sGByGqKlR6cHHrEebSWMoxOO6TOgYg06xfeYzxpx8HqMQjOKgNEbh4c
# m1Yx+ER/4BmWmYcvVHR9KtXwJWxmzUJCaS5OB9lp8JqO5+uAHvpGtQEAb39/h/vy
# 290isCYw16/uaLOz5Epchv5fogTBTh4o6SXWHam03FfMNVbmbMVuciTzfPSDt0i5
# xQWYtVkwVU+NGE4XUutX4zbaing53QYKNAa+NW9FiWcaoEwE1qTvk7ilsucPzdqC
# ikQpHyaaGCzHoDhveSLiJKgKRiDqee8KXfa/hkCoat9AtCihyd899kJ1kSlTO9fk
# ci5/CdKwmwXQIKh6OPueKr+OJ69XPx0V+RaaMAkkVtFb7/VwecFmFgsXFkAK8ulP
# aGYyIFOFqLMqH8ZuKiLVP5HkxDgSitJcWbaSf89TJuxNqh0vV1k4iwaQpcmQZhPK
# 49pNlj5j0cyw8B+xTYNDwnKvyoWgqKAb2cfzc6pCLk2GJLBwakKZ5YKC50XdhPlS
# yrqlLTb5otZRoYWFGKL1SqxxrBjRqg4qp1RvuxRcBQIDAQABo4ICAjCCAf4wHwYD
# VR0jBBgwFoAUaDfg67Y7+F8Rhvv+YXsIiGX0TkIwHQYDVR0OBBYEFL9ZTMS/Phgv
# GnXZm3XOrmDoJSIfMD0GA1UdIAQ2MDQwMgYFZ4EMAQMwKTAnBggrBgEFBQcCARYb
# aHR0cDovL3d3dy5kaWdpY2VydC5jb20vQ1BTMA4GA1UdDwEB/wQEAwIHgDATBgNV
# HSUEDDAKBggrBgEFBQcDAzCBtQYDVR0fBIGtMIGqMFOgUaBPhk1odHRwOi8vY3Js
# My5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRDb2RlU2lnbmluZ1JTQTQw
# OTZTSEEzODQyMDIxQ0ExLmNybDBToFGgT4ZNaHR0cDovL2NybDQuZGlnaWNlcnQu
# Y29tL0RpZ2lDZXJ0VHJ1c3RlZEc0Q29kZVNpZ25pbmdSU0E0MDk2U0hBMzg0MjAy
# MUNBMS5jcmwwgZQGCCsGAQUFBwEBBIGHMIGEMCQGCCsGAQUFBzABhhhodHRwOi8v
# b2NzcC5kaWdpY2VydC5jb20wXAYIKwYBBQUHMAKGUGh0dHA6Ly9jYWNlcnRzLmRp
# Z2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNENvZGVTaWduaW5nUlNBNDA5NlNI
# QTM4NDIwMjFDQTEuY3J0MAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggIBAMLk
# M/5BZB1j2xjjR9IkyDYtLrqS9IztErzl4ogf2dXuAgBJP1EKm/EN4oOi/BHxLW0T
# VuclGZ3aEa3/n3UlHxqmvKm+4elD5oh4sEOm7+J7ECV0HobeZhRiLmdyla1Mqbxw
# xp56AVvhG/++nf+AVzw95c671a3kb+6VXMDzZK1qcUh6zyLklZ/vfjKipry9KgMR
# sXd81I+PRr+99iRI+5pUsF7ixmS4vTldNh2r/VRFKLtXtTefZ20Q55Efu/8NefJf
# fD/+LLmHszB3LRlguFYOUGon7q8eQKi20PMW6PQb8az4mn6MfA1Y2x+L7HFDiy//
# VMOy5DqcKOHWqz/NZr7/VEPtywoLbHlUwNJyFY0wnQhzvPCg67YpDEYERDnggtpe
# OchKlJoqLKQInq6xDLTtco+ynR6IHnWRcz+oYhm6TdvRcmP7giiqObKEFXQwLsjS
# HsqRluk2FQ4DhG63+8gyD4rKQVoybP0obE7Gi2RYHOT0qwPos6GklZraht/capa7
# wos1gNKXJL7G6BaCXQWCyakT76ZOJOdHzHjJ2n+yBgKWWGBv186nrP5nfuRu0vJE
# HG74cy5oRwe3vme6ztPQy9VSgSrP+g67bZ6yPe+z09T7NczW4aXrXbMUdTb02zKQ
# sK8WEKfcvzBmZ115SwMuf3g34C5yRhOsWInfosmAMYIaYzCCGl8CAQEwfTBpMQsw
# CQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMTOERp
# Z2lDZXJ0IFRydXN0ZWQgRzQgQ29kZSBTaWduaW5nIFJTQTQwOTYgU0hBMzg0IDIw
# MjEgQ0ExAhAGQAJb/wxIlzKZ1GMgg8N7MA0GCWCGSAFlAwQCAQUAoHwwEAYKKwYB
# BAGCNwIBDDECMAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGC
# NwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIACtWGPPdpq1bh4O
# X5ELe7wBE0NPD4cLHHF/rbVQT1iDMA0GCSqGSIb3DQEBAQUABIICAIJ8a2zIF/1E
# gnLavcGNR4Nq6PV92AHS/FQGY/HUAugnVdYjTYxMOFMYlucK6WAjD9Gi+RToBV+k
# pdi9aRsp+4ubMaMxfouhEMP87fkdvkOf2goln2hFWOc6mfju6K3KCPIlCBPGFIEJ
# ULVOdnevVKcnIefSHhehNG8xGt/cnH3PpdpBvN/H4zg/l9ZuUtOlYLaqrCNPGCpQ
# KDuWkg9cGH2u43HagH8KffCSgFn9VkCFIVKdit3q5T4+JN9/fY7L6W2NOpNduz5h
# UZ4oN9hVYSHFAOKprGPwxF4xaWi7jERCXngVZW/lDNX42n8ZFz5TmQt5cRMZVAi/
# aelInszSWPVR3Jgrzr5+sw1HEp1Ps/WRB1q0hZMJ8Tb8cB6w/j1bbqAugqT7vEa8
# aOpJEGYIUK+dCONHjVaoS5KNA3hXeXye53J7BBfGoqlrN0YoN3DTRixtg1hFygTN
# APGDlgqTxQOGF7dFUCsJf/iPE+8zXvDMiH7FIDBbL6NXeGbtvupgyOLfH4xGCu6Z
# nZ+PycZn21p16vrxxeuejy1n8HdVXdUviOkdvibEPyKcbxvAO4jjK1hnSn0CEQZm
# JEYLqb5XSoV0gWgztiNFAVSZdLuXcoZq46YfV4szqzMyUWhqCCmuMgLeXgue8XDf
# 5x8lbtTYAvukspk0RhuaMpvyPUxACHAaoYIXOTCCFzUGCisGAQQBgjcDAwExghcl
# MIIXIQYJKoZIhvcNAQcCoIIXEjCCFw4CAQMxDzANBglghkgBZQMEAgEFADB3Bgsq
# hkiG9w0BCRABBKBoBGYwZAIBAQYJYIZIAYb9bAcBMDEwDQYJYIZIAWUDBAIBBQAE
# IPnp8dvZUJt2O/Ynzk54EDH7ItTF4oYx3yB3JelXsi7iAhBz0RIx1AFoKo/3OtG/
# wG/CGA8yMDI1MDYyNTExNTAwMFqgghMDMIIGvDCCBKSgAwIBAgIQC65mvFq6f5WH
# xvnpBOMzBDANBgkqhkiG9w0BAQsFADBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMO
# RGlnaUNlcnQsIEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFRydXN0ZWQgRzQgUlNB
# NDA5NiBTSEEyNTYgVGltZVN0YW1waW5nIENBMB4XDTI0MDkyNjAwMDAwMFoXDTM1
# MTEyNTIzNTk1OVowQjELMAkGA1UEBhMCVVMxETAPBgNVBAoTCERpZ2lDZXJ0MSAw
# HgYDVQQDExdEaWdpQ2VydCBUaW1lc3RhbXAgMjAyNDCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAL5qc5/2lSGrljC6W23mWaO16P2RHxjEiDtqmeOlwf0K
# MCBDEr4IxHRGd7+L660x5XltSVhhK64zi9CeC9B6lUdXM0s71EOcRe8+CEJp+3R2
# O8oo76EO7o5tLuslxdr9Qq82aKcpA9O//X6QE+AcaU/byaCagLD/GLoUb35SfWHh
# 43rOH3bpLEx7pZ7avVnpUVmPvkxT8c2a2yC0WMp8hMu60tZR0ChaV76Nhnj37DEY
# TX9ReNZ8hIOYe4jl7/r419CvEYVIrH6sN00yx49boUuumF9i2T8UuKGn9966fR5X
# 6kgXj3o5WHhHVO+NBikDO0mlUh902wS/Eeh8F/UFaRp1z5SnROHwSJ+QQRZ1fisD
# 8UTVDSupWJNstVkiqLq+ISTdEjJKGjVfIcsgA4l9cbk8Smlzddh4EfvFrpVNnes4
# c16Jidj5XiPVdsn5n10jxmGpxoMc6iPkoaDhi6JjHd5ibfdp5uzIXp4P0wXkgNs+
# CO/CacBqU0R4k+8h6gYldp4FCMgrXdKWfM4N0u25OEAuEa3JyidxW48jwBqIJqIm
# d93NRxvd1aepSeNeREXAu2xUDEW8aqzFQDYmr9ZONuc2MhTMizchNULpUEoA6Vva
# 7b1XCB+1rxvbKmLqfY/M/SdV6mwWTyeVy5Z/JkvMFpnQy5wR14GJcv6dQ4aEKOX5
# AgMBAAGjggGLMIIBhzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADAWBgNV
# HSUBAf8EDDAKBggrBgEFBQcDCDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgB
# hv1sBwEwHwYDVR0jBBgwFoAUuhbZbU2FL3MpdpovdYxqII+eyG8wHQYDVR0OBBYE
# FJ9XLAN3DigVkGalY17uT5IfdqBbMFoGA1UdHwRTMFEwT6BNoEuGSWh0dHA6Ly9j
# cmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFJTQTQwOTZTSEEyNTZU
# aW1lU3RhbXBpbmdDQS5jcmwwgZAGCCsGAQUFBwEBBIGDMIGAMCQGCCsGAQUFBzAB
# hhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wWAYIKwYBBQUHMAKGTGh0dHA6Ly9j
# YWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFJTQTQwOTZTSEEy
# NTZUaW1lU3RhbXBpbmdDQS5jcnQwDQYJKoZIhvcNAQELBQADggIBAD2tHh92mVvj
# OIQSR9lDkfYR25tOCB3RKE/P09x7gUsmXqt40ouRl3lj+8QioVYq3igpwrPvBmZd
# rlWBb0HvqT00nFSXgmUrDKNSQqGTdpjHsPy+LaalTW0qVjvUBhcHzBMutB6Hzele
# dbDCzFzUy34VarPnvIWrqVogK0qM8gJhh/+qDEAIdO/KkYesLyTVOoJ4eTq7gj9U
# FAL1UruJKlTnCVaM2UeUUW/8z3fvjxhN6hdT98Vr2FYlCS7Mbb4Hv5swO+aAXxWU
# m3WpByXtgVQxiBlTVYzqfLDbe9PpBKDBfk+rabTFDZXoUke7zPgtd7/fvWTlCs30
# VAGEsshJmLbJ6ZbQ/xll/HjO9JbNVekBv2Tgem+mLptR7yIrpaidRJXrI+UzB6vA
# lk/8a1u7cIqV0yef4uaZFORNekUgQHTqddmsPCEIYQP7xGxZBIhdmm4bhYsVA6G2
# WgNFYagLDBzpmk9104WQzYuVNsxyoVLObhx3RugaEGru+SojW4dHPoWrUhftNpFC
# 5H7QEY7MhKRyrBe7ucykW7eaCuWBsBb4HOKRFVDcrZgdwaSIqMDiCLg4D+TPVgKx
# 2EgEdeoHNHT9l3ZDBD+XgbF+23/zBjeCtxz+dL/9NWR6P2eZRi7zcEO1xwcdcqJs
# yz/JceENc2Sg8h3KeFUCS7tpFk7CrDqkMIIGrjCCBJagAwIBAgIQBzY3tyRUfNhH
# rP0oZipeWzANBgkqhkiG9w0BAQsFADBiMQswCQYDVQQGEwJVUzEVMBMGA1UEChMM
# RGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQD
# ExhEaWdpQ2VydCBUcnVzdGVkIFJvb3QgRzQwHhcNMjIwMzIzMDAwMDAwWhcNMzcw
# MzIyMjM1OTU5WjBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIElu
# Yy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFRydXN0ZWQgRzQgUlNBNDA5NiBTSEEyNTYg
# VGltZVN0YW1waW5nIENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
# xoY1BkmzwT1ySVFVxyUDxPKRN6mXUaHW0oPRnkyibaCwzIP5WvYRoUQVQl+kiPNo
# +n3znIkLf50fng8zH1ATCyZzlm34V6gCff1DtITaEfFzsbPuK4CEiiIY3+vaPcQX
# f6sZKz5C3GeO6lE98NZW1OcoLevTsbV15x8GZY2UKdPZ7Gnf2ZCHRgB720RBidx8
# ald68Dd5n12sy+iEZLRS8nZH92GDGd1ftFQLIWhuNyG7QKxfst5Kfc71ORJn7w6l
# Y2zkpsUdzTYNXNXmG6jBZHRAp8ByxbpOH7G1WE15/tePc5OsLDnipUjW8LAxE6lX
# KZYnLvWHpo9OdhVVJnCYJn+gGkcgQ+NDY4B7dW4nJZCYOjgRs/b2nuY7W+yB3iIU
# 2YIqx5K/oN7jPqJz+ucfWmyU8lKVEStYdEAoq3NDzt9KoRxrOMUp88qqlnNCaJ+2
# RrOdOqPVA+C/8KI8ykLcGEh/FDTP0kyr75s9/g64ZCr6dSgkQe1CvwWcZklSUPRR
# 8zZJTYsg0ixXNXkrqPNFYLwjjVj33GHek/45wPmyMKVM1+mYSlg+0wOI/rOP015L
# dhJRk8mMDDtbiiKowSYI+RQQEgN9XyO7ZONj4KbhPvbCdLI/Hgl27KtdRnXiYKNY
# CQEoAA6EVO7O6V3IXjASvUaetdN2udIOa5kM0jO0zbECAwEAAaOCAV0wggFZMBIG
# A1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFLoW2W1NhS9zKXaaL3WMaiCPnshv
# MB8GA1UdIwQYMBaAFOzX44LScV1kTN8uZz/nupiuHA9PMA4GA1UdDwEB/wQEAwIB
# hjATBgNVHSUEDDAKBggrBgEFBQcDCDB3BggrBgEFBQcBAQRrMGkwJAYIKwYBBQUH
# MAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBBBggrBgEFBQcwAoY1aHR0cDov
# L2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcnQw
# QwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lD
# ZXJ0VHJ1c3RlZFJvb3RHNC5jcmwwIAYDVR0gBBkwFzAIBgZngQwBBAIwCwYJYIZI
# AYb9bAcBMA0GCSqGSIb3DQEBCwUAA4ICAQB9WY7Ak7ZvmKlEIgF+ZtbYIULhsBgu
# EE0TzzBTzr8Y+8dQXeJLKftwig2qKWn8acHPHQfpPmDI2AvlXFvXbYf6hCAlNDFn
# zbYSlm/EUExiHQwIgqgWvalWzxVzjQEiJc6VaT9Hd/tydBTX/6tPiix6q4XNQ1/t
# YLaqT5Fmniye4Iqs5f2MvGQmh2ySvZ180HAKfO+ovHVPulr3qRCyXen/KFSJ8NWK
# cXZl2szwcqMj+sAngkSumScbqyQeJsG33irr9p6xeZmBo1aGqwpFyd/EjaDnmPv7
# pp1yr8THwcFqcdnGE4AJxLafzYeHJLtPo0m5d2aR8XKc6UsCUqc3fpNTrDsdCEkP
# lM05et3/JWOZJyw9P2un8WbDQc1PtkCbISFA0LcTJM3cHXg65J6t5TRxktcma+Q4
# c6umAU+9Pzt4rUyt+8SVe+0KXzM5h0F4ejjpnOHdI/0dKNPH+ejxmF/7K9h+8kad
# dSweJywm228Vex4Ziza4k9Tm8heZWcpw8De/mADfIBZPJ/tgZxahZrrdVcA6KYaw
# mKAr7ZVBtzrVFZgxtGIJDwq9gdkT/r+k0fNX2bwE+oLeMt8EifAAzV3C+dAjfwAL
# 5HYCJtnwZXZCpimHCUcr5n8apIUP/JiW9lVUKx+A+sDyDivl1vupL0QVSucTDh3b
# NzgaoSv27dZ8/DCCBY0wggR1oAMCAQICEA6bGI750C3n79tQ4ghAGFowDQYJKoZI
# hvcNAQEMBQAwZTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZ
# MBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNlcnQgQXNz
# dXJlZCBJRCBSb290IENBMB4XDTIyMDgwMTAwMDAwMFoXDTMxMTEwOTIzNTk1OVow
# YjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQ
# d3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBSb290
# IEc0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv+aQc2jeu+RdSjww
# IjBpM+zCpyUuySE98orYWcLhKac9WKt2ms2uexuEDcQwH/MbpDgW61bGl20dq7J5
# 8soR0uRf1gU8Ug9SH8aeFaV+vp+pVxZZVXKvaJNwwrK6dZlqczKU0RBEEC7fgvMH
# hOZ0O21x4i0MG+4g1ckgHWMpLc7sXk7Ik/ghYZs06wXGXuxbGrzryc/NrDRAX7F6
# Zu53yEioZldXn1RYjgwrt0+nMNlW7sp7XeOtyU9e5TXnMcvak17cjo+A2raRmECQ
# ecN4x7axxLVqGDgDEI3Y1DekLgV9iPWCPhCRcKtVgkEy19sEcypukQF8IUzUvK4b
# A3VdeGbZOjFEmjNAvwjXWkmkwuapoGfdpCe8oU85tRFYF/ckXEaPZPfBaYh2mHY9
# WV1CdoeJl2l6SPDgohIbZpp0yt5LHucOY67m1O+SkjqePdwA5EUlibaaRBkrfsCU
# tNJhbesz2cXfSwQAzH0clcOP9yGyshG3u3/y1YxwLEFgqrFjGESVGnZifvaAsPvo
# ZKYz0YkH4b235kOkGLimdwHhD5QMIR2yVCkliWzlDlJRR3S+Jqy2QXXeeqxfjT/J
# vNNBERJb5RBQ6zHFynIWIgnffEx1P2PsIV/EIFFrb7GrhotPwtZFX50g/KEexcCP
# orF+CiaZ9eRpL5gdLfXZqbId5RsCAwEAAaOCATowggE2MA8GA1UdEwEB/wQFMAMB
# Af8wHQYDVR0OBBYEFOzX44LScV1kTN8uZz/nupiuHA9PMB8GA1UdIwQYMBaAFEXr
# oq/0ksuCMS1Ri6enIZ3zbcgPMA4GA1UdDwEB/wQEAwIBhjB5BggrBgEFBQcBAQRt
# MGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBDBggrBgEF
# BQcwAoY3aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJl
# ZElEUm9vdENBLmNydDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsMy5kaWdp
# Y2VydC5jb20vRGlnaUNlcnRBc3N1cmVkSURSb290Q0EuY3JsMBEGA1UdIAQKMAgw
# BgYEVR0gADANBgkqhkiG9w0BAQwFAAOCAQEAcKC/Q1xV5zhfoKN0Gz22Ftf3v1cH
# vZqsoYcs7IVeqRq7IviHGmlUIu2kiHdtvRoU9BNKei8ttzjv9P+Aufih9/Jy3iS8
# UgPITtAq3votVs/59PesMHqai7Je1M/RQ0SbQyHrlnKhSLSZy51PpwYDE3cnRNTn
# f+hZqPC/Lwum6fI0POz3A8eHqNJMQBk1RmppVLC4oVaO7KTVPeix3P0c2PR3WlxU
# jG/voVA9/HYJaISfb8rbII01YBwCA8sgsKxYoA5AY8WYIsGyWfVVa88nq2x2zm8j
# LfR+cWojayL/ErhULSd+2DrZ8LaHlv1b0VysGMNNn3O3AamfV6peKOK5lDGCA3Yw
# ggNyAgEBMHcwYzELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMu
# MTswOQYDVQQDEzJEaWdpQ2VydCBUcnVzdGVkIEc0IFJTQTQwOTYgU0hBMjU2IFRp
# bWVTdGFtcGluZyBDQQIQC65mvFq6f5WHxvnpBOMzBDANBglghkgBZQMEAgEFAKCB
# 0TAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwHAYJKoZIhvcNAQkFMQ8XDTI1
# MDYyNTExNTAwMFowKwYLKoZIhvcNAQkQAgwxHDAaMBgwFgQU29OF7mLb0j575PZx
# SFCHJNWGW0UwLwYJKoZIhvcNAQkEMSIEIAG5To9TcbRe13Tm0k3YfqXq8u17Ee8O
# pMbQejHRlodmMDcGCyqGSIb3DQEJEAIvMSgwJjAkMCIEIHZ2n6jyYy8fQws6IzCu
# 1lZ1/tdz2wXWZbkFk5hDj5rbMA0GCSqGSIb3DQEBAQUABIICACs0fM5+tRJ5ZYvz
# 7SwWcKxmuahxTFBuLMhgnVi4V4soiZD6i1sV3KjVszD4GyfyNge7xLhFC8jJAAz2
# OCAVrBTshLs+2h7FX2w2ZGoV+sh8nnxJcY/1sLSNcU6yfKe6LrXHvRdJEaXB8w0P
# Qd/vrs7adJdtyetHoWNLWPb96j+AsBT2yL6kDLJ5E92dwHJMd5aABkYG5HUf3BJ0
# /rUKasBnrz9Mg4ALPkG0TMuZDi1n3rJOI3k5pD1daD0aleXSxhfDi4vONXIueqyg
# yJvcZNu5r7r3wA7wr5sRPCsBijY6ovjaZRZN3JUGBIWUEZRy157UFAoQD7njn3sC
# SwQUxyG/ygUcmgckhDfB5RvD+viOySXfs5kGutlOcg5A6xCyhHbD0RNukbD1Np8J
# ukIvMCO9rGnrd+exdkZiNT+qIi5b0Hq4IMuINXI3YBjBsWVR9JYm0BqfvNWUwcXD
# 0LonCTf4oF8uuJIaW4Nzv/0ludTBI8LFc03yD5pNLxzNjX4x7NQEDW6AzW4Zd2v4
# 4i5Mv44jgpt2Dhw8B7vkSD/Kqupjtkca8Y7cur9hnTXEBy6d1ZL5zM21er9pnSQB
# kWEYxYMw18spoKeGXz0iKzcazr6GLMoA+RPHJi0BAVj4YzHWSmJ6xua28YhnF/Yb
# 3xmTEo5RVHgQCnKlPduTpWdvTUBa
# SIG # End signature block
